version: "3.9"
services:
    proxy_server:
        image: jwilder/nginx-proxy:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static/index.html:/etc/nginx/html/index.html
            - ./static/assets:/etc/nginx/html/assets
            - /var/run/docker.sock:/tmp/docker.sock:ro
        container_name: proxy_server
        depends_on:
            - api
    api:
        image: kwagi/board:board-api
        ports:
            - 8080:8080
        container_name: api_server
